services:
  - type: web
    name: my-laravel-app
    env: docker
    build:
      dockerfile_path: Dockerfile
    plan: free
    ports:
      - port: 80
        target_port: 9000
    env_vars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: <base64:WEoOSDf3kW5Xgv7DzJz6iED6ND3SawLRxbLCn6pU95E=>  # Replace this with your actual Laravel application key
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1  # Ensure this matches the name of your MySQL service
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_database
      - key: DB_USERNAME
        value: your_user
      - key: DB_PASSWORD
        value: your_password
