services:
  - type: web
    name: my-laravel-app
    env: docker
    build:
      dockerfile_path: Dockerfile
      root_dir: project_tracking
    plan: free
    ports:
      - port: 80
        target_port: 9000
    env_vars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
         value: base64:WEoOSDf3kW5Xgv7DzJz6iED6ND3SawLRxbLCn6pU95E=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
