services:
  - type: web
    name: my-laravel-app
    env: docker
    build:
      dockerfile_path: Dockerfile
      root_dir: project_tracking
    plan: free
    ports:
      - port: 80
        target_port: 9000
    env_vars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: <YOUR_APP_KEY>
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_database
      - key: DB_USERNAME
        value: your_user
      - key: DB_PASSWORD
        value: your_password
